name: AzureTestMvcApp
trigger:
-main
 stages:
 -stage:build
  jobs:
  -job:build
   pool:
   name:default
   agent:
    name: DESKTOP-FJEKJE9
	
 variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

   workspace:
   clean:outputs
  steps:
    -task: NuGetToolInstaller@1
	-task: NuGetCommand@2
     inputs:
      restoreSolution: '$(solution)'
	  
 -task: VSBuild@1
	  inputs:
       solution: '$(solution)'
       msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
       platform: '$(buildPlatform)'
       configuration: '$(buildConfiguration)'
	
   -task: VSTest@2
    inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
	
   -task: PublishBuildArtifacts@1
    displayName: 'Publish artifact'
    inputs:
     PathtoPublish: '$(build.artifactstagingdirectory)'
     ArtifactName: '$(Parameters.ArtifactName)'
     condition: succeededOrFailed()
    
 stage:deiploy
  jobs:
  -job:DiployWeb
    pool:
	 name:default
   
   steps:
	 -task: powershell:'write self-host'
	 -task: DownloadBuildArtifacts@1
      inputs:
        buildType: 'specific'
        project: 'AzureDevTestProject'
        pipeline: '20230713.4 '
        buildVersionToDownload: 'latest'
        downloadType: 'single'
        downloadPath: '$(System.ArtifactsDirectory)'





