name: azureTestMvcApp_$(Date:yyyyddmm)($Rev:.r)
trigger:
- main
stages:
  - stage: BuildApplication 
    jobs:
      - job: Build
        pool:
         name: default
         demands: DESKTOP-FJEKJE9
        steps:
        - task: VSBuild@1
          inputs:
            solution: '**\*.sln'
            msbuildArgs: '''/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'''
        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)'
            ArtifactName: 'drop'
            publishLocation: 'Container'
  - stage: deploy
    jobs:
      - job: deployapplication
        pool:
         name: default
         demands: DESKTOP-FJEKJE9
        steps:
        - task: PowerShell@1
        #download artifact packages for deploy
        - task: DownloadBuildArtifacts@1
          inputs:
            buildType: 'current'
            downloadType: 'single'
            downloadPath: '$(System.ArtifactsDirectory)'
       
       
